### ISSUE TITLE
[BUG] Webhook configured, enabled but not working

### ISSUE THREAD

**Issue by eroji** [kubeshop/botkube#620] opened 2022-06-16 17:51 UTC
**Describe the bug**
I installed BotKube on my cluster that's running k8s 1.21.5. I have it configured to send Slack and webhook notifications. However, the webhook portion does not work. The receiving endpoint never got anything from BotKube.

**To Reproduce**
1. Install BotKube 0.12.4 via deploy-all-in-one.yaml
2. Change configmap accordingly
3. Update the secrets configuration
4. Make a change to a deployment in the monitored namespace

**Expected behavior**
There should be a webhook call triggered, but nothing was received

**Additional context**
Here is my config
```
Showing config for cluster 'dev-cluster'

resources:
- name: apps/v1/deployments
  namespaces:
    include:
    - dev-namespace
  events:
  - create
  - update
  - delete
  - error
  updateSetting:
    fields:
    - spec.template.spec.containers[*].image
    - status.availableReplicas
    includeDiff: true
recommendations: true
communications:
  slack:
    enabled: true
    channel: bot-kubernetes
    notiftype: short
  mattermost:
    enabled: false
    botName: ""
    url: ""
    token: ""
    team: ""
    channel: ""
  discord:
    enabled: false
    token: ""
    botid: ""
    channel: ""
  webhook:
    enabled: true
    url: https://webhook.endpoint/notify
  teams:
    enabled: false
    team: ""
    port: ""
    messagepath: ""
  elasticsearch:
    enabled: false
    username: ""
    server: ""
    skipTLSVerify: false
    awsSigning:
      enabled: false
      awsRegion: ""
      roleArn: ""
    index:
      name: ""
      type: ""
      shards: 0
      replicas: 0
settings:
  clustername: dev-cluster
  kubectl:
    enabled: false
    commands:
      verbs: []
      resources: []
    defaultNamespace: ""
    restrictAccess: false
  configwatcher: true
  upgradeNotifier: true
```

**Comment by pkosiec** [comment] 2022-06-17 06:34
Hi @eroji, could you please see the logs from the BotKube container?
A few days ago I tested webhook configuration and it worked fine, however I used the latest image from `develop`.

To confirm you encounter an issue on BotKube side, you can try to follow the guide https://www.botkube.io/contribute/webhook-develop/ and configure BotKube with sample web server which handles incoming requests.

**Comment by eroji** [comment] 2022-06-17 17:58
I just looked at the botkube pod, but it's overwhelmed with Slack unmarshalling errors since I have Slack configured. The deployment changes does create Slack notifications however, but not webhook calls.

I will try the echo-server you suggested.

**Comment by pkosiec** [comment] 2022-06-17 18:29
Right, the issue with Slack unmarshall errors when using Huddles is resolved in https://github.com/infracloudio/botkube/issues/579 and will be followed-up with https://github.com/infracloudio/botkube/issues/619. If the echo-server will work for you, please try to look for errors specific for the outgoing webhook integration.

Thank you!

**Comment by pkosiec** [comment] 2022-07-21 08:59
Hey @eroji, any news regarding your issue? Have you been able to test webhook integration with the echo server?

**Comment by pkosiec** [comment] 2022-08-25 10:59
Closing because of inactivity. I couldn't reproduce the issue. Feel free to reopen it if you have more questions 🙂

**Closed by pkosiec** 2022-08-25 10:59 UTC
Labels: question
