### ISSUE TITLE
helm chart options for specifying webhook configuration do not apply settings to the configMap

### ISSUE THREAD

**Issue by messedupryan** [kubeshop/botkube#1195] opened 2023-08-16 19:07 UTC
## Description

helm chart options to specify webhook configuration do not seem to update the `-runtime-config` configmap properly. This behavior affects using a `values.yaml` and using the `--set communications.default-group.webhook.enabled=true` method.

## Expected behavior

Running a `kubectl get cm botkube-runtime-config -o yaml -n botkube` should have a webhook block in the communications.default-group section.

## Actual behavior
The defailt-group does not contain any webhook configuration.

```
    communications:
      default-group:
        discord:
          channels:
            default:
              bindings:
                sources:
                - k8s-err-events
                - k8s-recommendation-events
        mattermost:
          channels:
            default:
              bindings:
                sources:
                - k8s-err-events
                - k8s-recommendation-events
        slack:
          channels:
            default:
              bindings:
                sources:
                - k8s-err-events
                - k8s-recommendation-events
        socketSlack:
          channels:
            default:
              bindings:
                sources:
                - k8s-err-events
                - k8s-recommendation-events
        teams:
          bindings:
            sources:
              - k8s-err-events
              - k8s-recommendation-events
```

## Steps to reproduce

1. Create a `values.yaml` with the following:
```yaml
communications:
  'default-group':
    webhook:
      enabled: true
      url: http://echoserver-echo-server
      bindings:
        sources:
          - k8s-all-events
```
2. apply this value using helm: 
`helm install --version v1.3.0 botkube --namespace botkube --create-namespace values.yaml botkube/botkube`

**Comment by pkosiec** [comment] 2023-08-17 07:30
Hey @messedupryan,

The `botkube-runtime-config` and `botkube-startup-config` ConfigMaps store just the data which can be configured with Botkube commands. This is the way how Botkube stores internal state, which is merged from both `helm upgrade` and `@Botkube` commands (like `@Botkube edit sourcebindings` or `@Botkube disable/enable notifications`).

In case of `botkube-runtime-config`, we store the source bindings configuration, which can be changed in runtime with `@Botkube edit sourcebindings`. Webhook integration doesn't have any interactivity, so that's why it is not included in the `runtime-config`. So, in other words, what you wrote is an expected behavior:
> helm chart options to specify webhook configuration do not seem to update the -runtime-config configmap properly.

Do you have any particular issue with webhook config?

**Comment by pkosiec** [comment] 2023-08-21 07:17
Hi @messedupryan, please ping me when you'll have time to describe the issue you encounter. Cheers!

**Comment by pkosiec** [comment] 2023-08-24 19:59
Hey @messedupryan, I'm closing this issue because of inactivity, but please feel free to reopen it with some additional context. I'd like to learn more what doesn't work for you or what we can improve. Thanks!

**Closed by pkosiec** 2023-08-24 19:59 UTC
Labels: needs-more-info
